# Generated by Django 4.2.6 on 2023-11-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_autor_options_alter_editor_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='autor',
            new_name='autores',
        ),
    ]
